### ISSUE TITLE
adjust package.json before first publish

### ISSUE THREAD

**Issue by sastan** [tw-in-js/twind.macro#1]
First: Great job! I'm happy to publish this as an initial preview for people to try it.

I would like to see a few small changes to the package.json beforehand.

- [ ] add the `files` property to bundle only those files that are needed
- [ ] add a description property
- [ ] add yourself as author
- [ ] add homepage, repository and bugs
- [ ] add keywords with twind, tailwind, babel macro

Maybe:

- [ ] should babel macro be a peer dependency
- [ ] change license to MIT (only because twind is using it and it maybe confusing to have different licenses)

Sadly i have very limited time at the moment. I maybe able to create an PR on the weekend. Otherwise please jump at it.

Thank you so much for this work!

**Comment by itsMapleLeaf** [comment]
I likely won't be doing much until the weekend myself (work picking back up 🙃)


> - should babel macro be a peer dependency
> - change license to MIT (only because twind is using it and it maybe confusing to have different licenses)

Agreed on both
